mytodolist/mytodolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
]

mytodolist/tasks/urls.py
from django.urls import path

from tasks import views

urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('', views.TaskListView.as_view(), name='list'),
    path('add/', views.TaskAddView.as_view(), name='add'),
    path('<int:task_id>/', views.TaskDetailsView.as_view(), name='details'),
    path('<int:task_id>/edit/', views.TaskEditView.as_view(), name='edit'),
    path('<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete'),
]

mytodolist/tasks/models.py
from django.db import models
from django.utils import timezone


class Task(models.Model):

    PRIORITY_CHOICES = [(1, 'Low'), (3, 'Medium'), (5, 'High')]

    title = models.CharField(max_length=160)
    description = models.TextField(null=True, blank=True)
    deadline = models.DateTimeField(null=True, blank=True)

    priority = models.IntegerField(
        null=True, blank=False, choices=PRIORITY_CHOICES)

    created_at = models.DateTimeField(editable=False, default=timezone.now)

    task_list = models.ForeignKey(
        'TaskList',
        on_delete=models.CASCADE,
        related_name='tasks',
        null=True,
        blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('created_at', )


class TaskList(models.Model):

    title = models.CharField(max_length=80, unique=True)

mytodolist/tasks/forms.py
from django import forms

from tasks import models


class TaskForm(forms.Form):
    title = forms.CharField(label='Title', max_length=160)
    description = forms.CharField(
        label='Description', widget=forms.Textarea, required=False)
    deadline = forms.DateTimeField(label='Deadline', required=False)
    priority = forms.ChoiceField(
        label="Priority", choices=models.Task.PRIORITY_CHOICES, required=False)


class TaskModelForm(forms.ModelForm):
    class Meta:
        model = models.Task
        fields = ['title', 'description', 'deadline', 'priority']

    

mytodolist/tasks/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import View
from django.utils.timezone import now
from django.http import Http404

from tasks.models import Task
from tasks.forms import TaskForm, TaskModelForm

class IndexView(View):

    def get(self, request, *args, **kwargs):
        context = {
            'current_time': now(),
        }
        return render(request, 'tasks/index.html', context=context)


class TaskListView(View):

    def get(self, request, *args, **kwargs):
        context = {}
        tasks = Task.objects.all()
        if 'q' in request.GET:
            context['tasks_q'] = request.GET['q']
            tasks = tasks.filter(title__contains=request.GET['q'])

        context['task_list'] = tasks
        return render(request, 'tasks/task_list.html', context=context)


class TaskDetailsView(View):

    def get(self, request, task_id):
        try:
            context = {
                'task_id': task_id,
                'task': Task.objects.get(id=task_id)
            }
            return render(request, 'tasks/task_details.html', context=context)
        except Task.DoesNotExist:
            raise Http404('Task does not exist')




class TaskEditView(View):

    def get(self, request, task_id):
        try:
            task = Task.objects.get(id=task_id)
        except Task.DoesNotExist:
            raise Http404('Task does not exist')

        form = TaskModelForm(instance=task)
        context = {
            'task': task,
            'form': form
        }
        return render(request, 'tasks/task_edit.html', context=context)

    def post(self, request, task_id):

        try:
            task = Task.objects.get(id=task_id)
        except Task.DoesNotExist:
            raise Http404('Task does not exist')

        form = TaskModelForm(request.POST, instance=task)
        if form.is_valid():

            form.save()
            return HttpResponseRedirect(reverse('list'))

        context = {
            'form': form,
            'task': task
        }
        return render(request, 'tasks/task_edit.html', context=context)


class TaskAddView(View):

    def get(self, request):

        form = TaskModelForm()
        context = {
            'form': form
        }
        return render(request, 'tasks/task_add.html', context=context)

    def post(self, request):

        form = TaskModelForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('list'))

        context = {
            'form': form,
        }
        return render(request, 'tasks/task_add.html', context=context)




class TaskDeleteView(View):

    def get(self, request, task_id):
        task = Task.objects.get(id=task_id)
        context = {'task': task}
        return render(request, 'tasks/task_delete.html', context=context)

    def post(self, request, task_id):
        Task.objects.get(id=task_id).delete()
        return HttpResponseRedirect(reverse('list'))

mytodolist/tasks/templates/tasks/base-style.html
{# base/index.html #}
{% load static %}
<!doctype html>
<html class="no-js" lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>mytodolist</title>
    <link rel="stylesheet" href="{% static 'css/foundation.css' %}">
    <link rel="stylesheet" href="{% static 'tasks/app.css' %}">
</head>

<body>
    <div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="responsive-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">My Todo List</li>
      <li class="has-submenu">
        <a href="{% url 'list' %}">My Tasks</a>
      </li>
      <li><a href="{% url 'add' %}">Add task</a></li>

    </ul>
  </div>
  <div class="top-bar-right">
    <form action="{% url 'list'%}">
      <ul class="menu">
    
      <li><input name="q" type="search" placeholder="Search" 
        value={{tasks_q}}></li>
      <li><button type="button" class="button">Search</button></li>
    
    </ul>
    </form>
  </div>
</div>


    <div class="grid-container">
        <div class="grid-x grid-margin-x">
            <div class="cell">
                {% block page_content %}
                {% endblock %}
            </div>
        </div>
    </div>
    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.js' %}"></script>
    <script src="{% static 'tasks/app.js' %}"></script>
</body>

</html>

mytodolist/tasks/templates/tasks/base.html
{# base/index.html #}

{% load static %}

<!DOCTYPE html>
<html lang="en"> 
<head>
    <link rel="stylesheet" href="{% static 'tasks/app.css' %}">
</head>
<body>

    {% block page_content %}
    {% endblock %}

        
</body>    
</html>

mytodolist/tasks/templates/tasks/index.html
{# tasks/index.html #}

{% extends 'tasks/base.html' %}

{% block page_content %}
    <h1>Tasks App index view.</h1>
    <p>Current time: {{current_time}}</p>
{% endblock %}

mytodolist/tasks/templates/tasks/task_add.html
{# tasks/task_edit.html #}

{% extends 'tasks/base-style.html' %}

{% block page_content %}
    <h1>Tasks - Add View.</h1>

    <form action="{% url 'add' %}" method="post">
    {% csrf_token %}
    
    {{form.as_p}}
    
    <input type="submit" class="button" value="Save">
    </form>

{% endblock %}

mytodolist/tasks/templates/tasks/task_delete.html
{# tasks/task_list.html #}

{% extends 'tasks/base-style.html' %}

{% block page_content %}
    <h1>Tasks - Delet View.</h1>

    <p>Da li si siguran?</p>

    <form action="{% url 'delete' task_id=task.id %}" method="POST">
        {% csrf_token %}
        <input type="submit" class="button alert" value="Delete">
    </form>


{% endblock %}

mytodolist/tasks/templates/tasks/task_details.html
{# tasks/task_list.html #}

{% extends 'tasks/base-style.html' %}

{% block page_content %}
    <h1>{{task.title}}.</h1>

    <p> {{task.description}}</p>

    <p>Priority: {{task.get_priority_display}}</p>
    
    <p>Deadline: {{task.deadline}}</p>


    <a href="{% url 'edit' task_id=task.id %}" class="button">Edit</a>
    <a href="{% url 'delete' task_id=task.id %}" class="button alert">Delete</a>
{% endblock %}

mytodolist/tasks/templates/tasks/task_edit.html
{# tasks/task_edit.html #}

{% extends 'tasks/base-style.html' %}

{% block page_content %}
    <h1>Tasks - Edit View.</h1>

    <form action="{% url 'edit' task_id=task.id%}" method="post">
    {% csrf_token %}
    
    {{form.as_p}}
    
    <input type="submit" class="button" value="Save">
    </form>

{% endblock %}

mytodolist/tasks/templates/tasks/task_list.html
{# tasks/task_list.html #}

{% extends 'tasks/base-style.html' %}

{% block page_content %}
    <h1>Tasks - List View.</h1>

    <ul>
    {% for task in task_list %}
        <li> 
            <a href="{% url 'details' task_id=task.id %}">{{ task.title }}</a>
        </li>
    {% endfor %}
    </ul>

{% endblock %}