usedcarswebsite/carsapp/urls.py
from django.urls import path
from carsapp import views

urlpatterns = [
    path('', views.CarListView.as_view(), name='car_list'),
    path('add/', views.CarAddView.as_view(), name='car_add'),
    path('<int:car_id>/', views.CarDetailsView.as_view(), name='car_details'),
    path('<int:car_id>/', views.CarDetailsView.as_view(), name='car_details'),
    path('<int:car_id>/edit/', views.CarEditView.as_view(), name='car_edit'),
    path('<int:car_id>/delete/', views.CarDeleteView.as_view(), name='car_delete'),
]

usedcarswebsite/usedcarswebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/', include('carsapp.urls'))
]

usedcarswebsite/carsapp/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Car(models.Model):

    ENGINE_BENZIN = 'b'
    ENGINE_DIESEL = 'd'

    ENGINE_CHOICES = [
        (ENGINE_BENZIN, _('Benzin')),
        (ENGINE_DIESEL, _('Diesel')),
    ]

    title = models.CharField(max_length=140)
    link = models.URLField(verbose_name="Advertisement Link")
    company = models.CharField(max_length=80)
    year = models.IntegerField()
    engine_type = models.CharField(max_length=1, choices=ENGINE_CHOICES)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title', )

usedcarswebsite/carsapp/forms.py
from django import forms
from carsapp import models


class CarForm(forms.Form):
    title = forms.CharField(label='Title', max_length=255)
    link = forms.URLField(label='External link', max_length=255)
    company = forms.CharField(label='Company', max_length=255)
    year = forms.IntegerField(label='Year')
    engine_type = forms.ChoiceField(
        label="Engine Type", choices=models.Car.ENGINE_CHOICES)


class CarModelForm(forms.ModelForm):

    class Meta:
        model = models.Car
        fields = ['title', 'link', 'company', 'year', 'engine_type']

usedcarswebsite/carsapp/views.py
from django.shortcuts import render

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils.timezone import now
from django.views import View
from django.urls import reverse

from carsapp.models import Car
from carsapp.forms import CarModelForm

class CarListView(View):

    def get(self, request, **kwargs):
        context = {
            'cars': Car.objects.all()
        }
        return render(request, 'carsapp/car_list.html', context=context)


class CarDetailsView(View):

    def get(self, request, car_id):
        context = {
            'car': Car.objects.get(id=car_id)
        }
        return render(request, 'carsapp/car_details.html', context=context)


class CarEditView(View):

    def get(self, request, car_id):
        car = Car.objects.get(id=car_id)
        
        form = CarModelForm(instance=car)
        
        context = {
            'form': form
        }
        return render(request, 'carsapp/car_edit.html', context=context)

    def post(self, request, car_id):
        car = Car.objects.get(id=car_id)
        car_form = CarModelForm(request.POST, instance=car)
        if car_form.is_valid():
            car_form.save()
            return HttpResponseRedirect(
                reverse('car_details', kwargs={'car_id': car_id}))
        
        context = {}
        context['form'] = car_form
        return render(request, 'carsapp/car_edit.html', context=context)


class CarAddView(View):

    def get(self, request):
        form = CarModelForm()
        context = {
            'form': form,
            'add_new': True
        }
        return render(request, 'carsapp/car_edit.html', context=context)

    def post(self, request):
        car_form = CarModelForm(request.POST)
        if car_form.is_valid():
            new_car = car_form.save()
            return HttpResponseRedirect(
                reverse('car_details', kwargs={'car_id': new_car.id}))

        context = {
            'form': car_form,
            'add_new': True
        }
        return render(request, 'carsapp/car_edit.html', context=context)


class CarDeleteView(View):
    def get(self, request, **kwargs):
        context = {}

        return render(request, 'carsapp/car_delete.html', context=context)

usedcarswebsite/carsapp/templates/carsapp/base.html
{# carsapp/base.html #}
{% load staticfiles i18n static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'carsapp/app.css' %}">
    <title>{%block title %} Used cars site{% endblock %}</title>
</head>

<body>
    <header>
        HEADER
    </header>
    {% block page_content %}
    {% endblock %}
    <footer>
        FOOTER
    </footer>
</body>

</html>

usedcarswebsite/carsapp/templates/carsapp/car_delete.html
{# carsapp/index.html #}

{% extends 'carsapp/base.html' %}

{% block title %}
carsapp
{% endblock %}


{% block page_content %}
<h1>Car Delete view.</h1>
{% endblock %}

usedcarswebsite/carsapp/templates/carsapp/car_details.html
{# carsapp/car_details.html #}

{% extends 'carsapp/base.html' %}

{% block title %}
carsapp
{% endblock %}


{% block page_content %}
<h1>Car Details view.</h1>

<p> Title: <strong>{{car.title}}</strong> </p>
<p> Company: <strong>{{car.company}}</strong> </p>
<p> Year: <strong>{{car.year}}</strong> </p>
<p> Engine type: <strong>{{car.get_engine_type_display}}</strong> </p>


<p>
    <a href="{% url 'car_edit' car_id=car.id %}">Edit</a>
</p>
<p>
    <a href="{% url 'car_delete' car_id=car.id %}">Delete</a>
</p>

<p>
    <a href="{% url 'car_list' %}">Back to list</a>
</p>


{% endblock %}

usedcarswebsite/carsapp/templates/carsapp/car_edit.html
{# carsapp/car_edit.html #}

{% extends 'carsapp/base.html' %}

{% block title %}
carsapp
{% endblock %}



{% block page_content %}
{% if add_new %}
<h1>Car Add view.</h1>
{% else %}
<h1>Car Edit view.</h1>
{% endif %}

<form action="" method="post" novalidate>
    {% csrf_token %}

    {{form.as_p}}

    <input type="submit" value="submit">

</form>


{% endblock %}

usedcarswebsite/carsapp/templates/carsapp/car_list.html
{# carsapp/car_list.html #}

{% extends 'carsapp/base.html' %}

{% block title %}
carsapp
{% endblock %}


{% block page_content %}
<h1>Car List view.</h1>

<ul>
{% for car in cars %}
    <li>
    <a href="{% url 'car_details' car_id=car.id %}">{{car.title}}</a>
    </li>

{% endfor %}
</ul>

<p>
    <a href="{% url 'car_add' %}">Add new car</a>
</p>



{% endblock %}